### ISSUE TITLE
Error when search using boolean /exact match | Omeka 2.7.0

### ISSUE THREAD

**Issue by saponidas** [omeka/plugin-Reports#31]
When searching with these option form the home page, it brokes. Deactiving the plugin works fine

The plugins seems to work fine, but the next table **reports_repor**ts is not in the DB. The existing plugin tables are:
| omeka_reports
| omeka_reports_files
| omeka_reports_items

ERROR:
Zend_Db_Statement_Mysqli_Exception
Mysqli prepare error: Table 'db.omeka_reports_reports' doesn't exist
```
Zend_Db_Statement_Mysqli_Exception: Mysqli prepare error: Table 'db.omeka_reports_reports' doesn't exist in /var/www/html/application/libraries/Zend/Db/Statement/Mysqli.php:77
Stack trace:

#0 /var/www/html/application/libraries/Zend/Db/Statement.php(115): Zend_Db_Statement_Mysqli->_prepare('SELECT `reports...')
#1 /var/www/html/application/libraries/Zend/Db/Adapter/Mysqli.php(388): Zend_Db_Statement->__construct(Object(Zend_Db_Adapter_Mysqli), 'SELECT `reports...')
#2 /var/www/html/application/libraries/Zend/Db/Adapter/Abstract.php(479): Zend_Db_Adapter_Mysqli->prepare('SELECT `reports...')
#3 /var/www/html/application/libraries/Zend/Db/Adapter/Abstract.php(756): Zend_Db_Adapter_Abstract->query('SELECT `reports...', Array)
#4 /var/www/html/application/libraries/Omeka/Db.php(80): Zend_Db_Adapter_Abstract->fetchRow(Object(Omeka_Db_Select), Array)
#5 /var/www/html/application/libraries/Omeka/Db/Table.php(669): Omeka_Db->__call('fetchRow', Array)
#6 /var/www/html/application/libraries/Omeka/Db/Table.php(214): Omeka_Db_Table->fetchObject(Object(Omeka_Db_Select), Array)
#7 /var/www/html/application/libraries/globals.php(1879): Omeka_Db_Table->find(1)
#8 /var/www/html/application/views/scripts/search/index.php(20): get_record_by_id('Reports_Report', 1)
#9 /var/www/html/application/libraries/Omeka/View.php(114): include('/var/www/html/a...')
#10 /var/www/html/application/libraries/Zend/View/Abstract.php(888): Omeka_View->_run('/var/www/html/a...')
#11 /var/www/html/application/libraries/Zend/Controller/Action/Helper/ViewRenderer.php(912): Zend_View_Abstract->render(NULL)
#12 /var/www/html/application/libraries/Zend/Controller/Action/Helper/ViewRenderer.php(933): Zend_Controller_Action_Helper_ViewRenderer->renderScript('search/index.ph...', NULL)
#13 /var/www/html/application/libraries/Zend/Controller/Action/Helper/ViewRenderer.php(972): Zend_Controller_Action_Helper_ViewRenderer->render()
#14 /var/www/html/application/libraries/Zend/Controller/Action/HelperBroker.php(277): Zend_Controller_Action_Helper_ViewRenderer->postDispatch()
#15 /var/www/html/application/libraries/Zend/Controller/Action.php(527): Zend_Controller_Action_HelperBroker->notifyPostDispatch()
#16 /var/www/html/application/libraries/Zend/Controller/Dispatcher/Standard.php(308): Zend_Controller_Action->dispatch('indexAction')
#17 /var/www/html/application/libraries/Zend/Controller/Front.php(954): Zend_Controller_Dispatcher_Standard->dispatch(Object(Zend_Controller_Request_Http), Object(Zend_Controller_Response_Http))
#18 /var/www/html/application/libraries/Zend/Application/Bootstrap/Bootstrap.php(105): Zend_Controller_Front->dispatch()
#19 /var/www/html/application/libraries/Zend/Application.php(384): Zend_Application_Bootstrap_Bootstrap->run()
#20 /var/www/html/application/libraries/Omeka/Application.php(73): Zend_Application->run()
#21 /var/www/html/index.php(23): Omeka_Application->run()
#22 {main}
```

**Comment by zerocrates** [comment]
That's strange... the Reports plugin defines the correct table name so that's what should be getting used.

If you don't care about actually searching on reports, you could exclude them from indexing in the Search settings.
